sudo: false
language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gcc-arm-embedded
    - $HOME/.stack
    - $HOME/.camkes
    - $HOME/.ccache

addons:
  apt:
    sources:
      - hvr-ghc
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - ghc-7.8.4
      - cabal-install-1.22
      - alex-3.1.4
      - happy-1.19.5
      - lib32ncurses5
      - libev-dev
      - gcc-4.8
      - libgmp3-dev
      - zlib1g-dev
      - make
      - libtinfo-dev
      - libncurses5-dev
      - realpath
      - python-pip
      - libxml2-utils
      - u-boot-tools
      - python2.7-dev
      - ninja-build
      - libsqlite3-dev
      - libcunit1-dev
      - clang-3.4
      - expect
      - cmake
      - cmake-data

before_install:
  # Add paths for Haskell tools
  - export PATH="/opt/ghc/7.8.4/bin:/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH"
  # Download and unpack the stack executable
  - mkdir -p $HOME/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH="$HOME/.local/bin:$PATH"
  - stack --version
  # Set up GHC 7.10.3 for stack builds
  - stack --resolver=lts-5.3 setup
  # Download and unpack the ARM embedded toolchain
  - if [ ! -d $HOME/.gcc-arm-embedded/*/bin ];
    then
      mkdir -p $HOME/.gcc-arm-embedded;
      wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C $HOME/.gcc-arm-embedded;
    fi
  - export PATH="$PWD:$(echo $HOME/.gcc-arm-embedded/*/bin):$PATH"
  - gcc --version
  - arm-none-eabi-gcc --version
  - ghc --version
  - cabal --version
  - alex --version
  - happy --version
  # - export SMACCM_BRANCH=$TRAVIS_BRANC

script:
  - cd scripts
  - ./main.sh

env:
#  - DEFCONFIG=smaccmpilot_defconfig IMAGE_NAME=capdl-loader-experimental-image-arm-exynos5
  - DEFCONFIG=smaccmpilot-tk1_defconfig IMAGE_NAME=capdl-loader-experimental-image-arm-tk1
